// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {stdJson} from "forge-std/StdJson.sol";
import {BlobsitterInstance} from "src/BlobsitterInstance.sol";
import {InstanceTestBase} from "test/helpers/InstanceTestBase.sol";
import {TestVec} from "test/helpers/TestVec.sol";

/// Test-plan Layer 4 (local half): declareFor with a REAL c-kzg opening of a real §4
/// pattern blob, verified by the local EVM's real point-evaluation precompile at the
/// contract-computed Fiat–Shamir z. The fixture is generated by tools/kzg-fixture
/// (embedded Ethereum setup — no ceremony) and regenerated + diffed in CI.
///
/// z binds the instance address and prior state, so the instance is deployed at the
/// fixture's dummy address and brought to priorLeafCount with zero-blob declarations.
contract FixtureKzgTest is InstanceTestBase {
    using stdJson for string;

    string internal json;
    BlobsitterInstance internal fx;

    function setUp() public override {
        super.setUp();
        json = vm.readFile("test/fixtures/kzg_opening.json");
        address at = json.readAddress(".instance");
        BlobsitterInstance.Params memory p = _params();
        deployCodeTo("BlobsitterInstance.sol:BlobsitterInstance", abi.encode(p), at);
        fx = BlobsitterInstance(at);
        _declareOn(fx, uint64(json.readUint(".priorLeafCount"))); // reach n0
    }

    function _fixtureDeclaration()
        internal
        view
        returns (BlobsitterInstance.Declaration memory d, BlobsitterInstance.BlobOpening[] memory o)
    {
        d.nonce = fx.declarationNonce();
        d.deadline = uint64(block.timestamp + 1 hours);
        d.blobVersionedHashes = json.readBytes32Array(".blobVersionedHashes");
        d.newSubtreePeaks = json.readBytes32Array(".newSubtreePeaks");
        d.newLeafCount = uint64(json.readUint(".newLeafCount"));
        o = new BlobsitterInstance.BlobOpening[](1);
        o[0] = BlobsitterInstance.BlobOpening({
            y: json.readBytes32(".y"),
            commitment: json.readBytes(".commitment"),
            kzgProof: json.readBytes(".kzgProof")
        });
    }

    function test_fixture_realKzgOpeningThroughDeclareFor() public {
        // The fixture's z must be exactly what the contract computes on-chain.
        assertEq(
            uint256(
                fx.fiatShamirZ(
                    json.readBytes32Array(".blobVersionedHashes"),
                    json.readBytes32Array(".priorPeaks"),
                    json.readBytes32Array(".newSubtreePeaks"),
                    uint64(json.readUint(".priorLeafCount")),
                    uint64(json.readUint(".newLeafCount"))
                )
            ),
            json.readUint(".z"),
            "fixture z != contract z"
        );

        (BlobsitterInstance.Declaration memory d, BlobsitterInstance.BlobOpening[] memory o) =
            _fixtureDeclaration();
        vm.blobhashes(d.blobVersionedHashes);
        fx.declareFor(d, _sign(fx.declarationDigest(d)), o, goodProof);

        assertEq(fx.leafCount(), d.newLeafCount, "advanced");
        (bytes32[] memory want,) = TestVec.buildPeaks(d.newLeafCount);
        assertEq(fx.allPeaks(), want, "pattern blob content matches the pattern peaks");
    }

    /// The real precompile rejects a real-but-wrong opening: correct commitment and
    /// proof, perturbed claimed evaluation.
    function test_fixture_wrongYRejected() public {
        (BlobsitterInstance.Declaration memory d, BlobsitterInstance.BlobOpening[] memory o) =
            _fixtureDeclaration();
        o[0].y = bytes32(uint256(o[0].y) ^ 1);
        vm.blobhashes(d.blobVersionedHashes);
        bytes memory sig = _sign(fx.declarationDigest(d));
        vm.expectRevert(
            abi.encodeWithSelector(BlobsitterInstance.PointEvaluationFailed.selector, uint256(0))
        );
        fx.declareFor(d, sig, o, goodProof);
    }
}
