//! Generates `contracts/test/fixtures/kzg_opening.json`: a REAL KZG opening for a real
//! blob laid out per the normative chunk-to-blob mapping, verifiable by the EIP-4844
//! point-evaluation precompile at the Fiat–Shamir point the instance computes on-chain.
//!
//! The fixture declaration appends m = 3 pattern chunks at prior leaf count n₀ = 5 (the
//! fs_z.json shape) on the fixed dummy instance address the other vectors use. Because
//! z is instance- and state-bound, the forge test must deploy at that address and reach
//! n₀ = 5 first.
//!
//! Deterministic output; CI regenerates and diffs it. Never hand-edit — regenerate.

use blobsitter_reference::{decompose, fs_z, testvec, Hash};
use sha2::{Digest, Sha256};

const INSTANCE: [u8; 20] = [
    0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee,
    0xff, 0x00, 0x11, 0x22, 0x33,
];
const N0: u64 = 5;
const M: u64 = 3;

fn hx(bytes: &[u8]) -> String {
    let mut s = String::from("0x");
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

fn main() {
    // Chunk-to-blob mapping: local chunk u -> field element u, byte 0 zero (so the
    // element stays below the BLS modulus), bytes 1..31 the chunk; trailing elements zero.
    let mut blob_bytes = vec![0u8; 131_072];
    for u in 0..M {
        let chunk = testvec::chunk(N0 + u);
        let elem = (u as usize) * 32;
        blob_bytes[elem + 1..elem + 32].copy_from_slice(&chunk);
    }

    let settings = c_kzg::ethereum_kzg_settings(0);
    let blob = c_kzg::Blob::from_bytes(&blob_bytes).expect("valid blob");
    let commitment = settings.blob_to_kzg_commitment(&blob).expect("commitment");

    // EIP-4844 versioned hash: 0x01 ‖ sha256(commitment)[1:].
    let mut vh: Hash = Sha256::digest(commitment.to_bytes().as_slice()).into();
    vh[0] = 0x01;

    // Publisher-side declaration pieces, then the Fiat–Shamir point the contract will
    // compute on-chain.
    let prior_peaks = testvec::build(N0).peaks();
    let heights = decompose(N0, M);
    let mut subtrees = Vec::new();
    let mut pos = N0;
    for &h in &heights {
        subtrees.push(testvec::subtree_root(pos, h));
        pos += 1u64 << h;
    }
    let z = fs_z(&INSTANCE, &[vh], &prior_peaks, &subtrees, N0, N0 + M);

    let z_point = c_kzg::Bytes32::from_bytes(&z).expect("z in field");
    let (proof, y) = settings.compute_kzg_proof(&blob, &z_point).expect("proof");

    // Self-check: the opening we emit must verify.
    assert!(
        settings
            .verify_kzg_proof(&commitment.to_bytes(), &z_point, &y, &proof.to_bytes())
            .expect("verify runs"),
        "generated opening does not verify"
    );

    let out = serde_json::json!({
        "_purpose": "REAL KZG opening for the forge suite (test-plan Layer 4); generated by tools/kzg-fixture — never hand-edit",
        "instance": hx(&INSTANCE),
        "priorLeafCount": N0,
        "newLeafCount": N0 + M,
        "priorPeaks": prior_peaks.iter().map(|p| hx(p)).collect::<Vec<_>>(),
        "newSubtreePeaks": subtrees.iter().map(|p| hx(p)).collect::<Vec<_>>(),
        "blobVersionedHashes": [hx(&vh)],
        "commitment": hx(commitment.to_bytes().as_slice()),
        "kzgProof": hx(proof.to_bytes().as_slice()),
        "y": hx(y.as_slice()),
        "z": hx(&z),
    });

    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../contracts/test/fixtures/kzg_opening.json"
    );
    std::fs::write(path, format!("{}\n", serde_json::to_string_pretty(&out).unwrap()))
        .expect("write fixture");
    println!("wrote contracts/test/fixtures/kzg_opening.json");
}
