//! Generates the REAL KZG opening fixtures for the forge suite: real blobs laid out
//! per the normative chunk-to-blob mapping, verifiable by the EIP-4844 point-evaluation
//! precompile at the Fiat–Shamir point the instance computes on-chain.
//!
//! Two fixtures, both on the fixed dummy instance address the vectors use (z is
//! instance- and state-bound, so tests deploy at that address):
//! - `kzg_opening.json` — m = 3 appended at n₀ = 5 (the fs_z.json shape); the local-EVM
//!   test reaches n₀ with zero-blob declarations first.
//! - `kzg_opening_genesis.json` — m = 8 at n₀ = 0: a GENESIS declaration with no prior
//!   history, so the real-verifier fork test (where every declaration needs a real
//!   proof) can replay it as the very first state transition.
//!
//! Deterministic output; CI regenerates and diffs both. Never hand-edit — regenerate.

use blobsitter_reference::{decompose, fs_z, testvec, Hash};
use sha2::{Digest, Sha256};

const INSTANCE: [u8; 20] = [
    0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee,
    0xff, 0x00, 0x11, 0x22, 0x33,
];

fn hx(bytes: &[u8]) -> String {
    let mut s = String::from("0x");
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

fn emit_fixture(n0: u64, m: u64, file: &str) {
    // Chunk-to-blob mapping: local chunk u -> field element u, byte 0 zero (so the
    // element stays below the BLS modulus), bytes 1..31 the chunk; trailing zeros.
    let mut blob_bytes = vec![0u8; 131_072];
    for u in 0..m {
        let chunk = testvec::chunk(n0 + u);
        let elem = (u as usize) * 32;
        blob_bytes[elem + 1..elem + 32].copy_from_slice(&chunk);
    }

    let settings = c_kzg::ethereum_kzg_settings(0);
    let blob = c_kzg::Blob::from_bytes(&blob_bytes).expect("valid blob");
    let commitment = settings.blob_to_kzg_commitment(&blob).expect("commitment");

    // EIP-4844 versioned hash: 0x01 ‖ sha256(commitment)[1:].
    let mut vh: Hash = Sha256::digest(commitment.to_bytes().as_slice()).into();
    vh[0] = 0x01;

    // Publisher-side declaration pieces, then the Fiat–Shamir point the contract will
    // compute on-chain.
    let prior_peaks = testvec::build(n0).peaks();
    let heights = decompose(n0, m);
    let mut subtrees = Vec::new();
    let mut pos = n0;
    for &h in &heights {
        subtrees.push(testvec::subtree_root(pos, h));
        pos += 1u64 << h;
    }
    let z = fs_z(&INSTANCE, &[vh], &prior_peaks, &subtrees, n0, n0 + m);

    let z_point = c_kzg::Bytes32::from_bytes(&z).expect("z in field");
    let (proof, y) = settings.compute_kzg_proof(&blob, &z_point).expect("proof");

    // Self-check: the opening we emit must verify.
    assert!(
        settings
            .verify_kzg_proof(&commitment.to_bytes(), &z_point, &y, &proof.to_bytes())
            .expect("verify runs"),
        "generated opening does not verify"
    );

    // Triangulation: the reference barycentric evaluator (compiled into the circuit
    // guests) must agree with c-kzg's evaluation of the same real blob at the same z.
    // Together with the Python evaluator behind vectors/public_values.json, the
    // independent implementations pin the evaluation semantics.
    let chunks: Vec<_> = (n0..n0 + m).map(testvec::chunk).collect();
    let elements = blobsitter_reference::blob::elements_from_chunks(&chunks);
    let y_ref = blobsitter_reference::blob::barycentric_eval(&elements, &z);
    assert_eq!(
        y_ref.as_slice(),
        y.as_slice(),
        "reference barycentric eval disagrees with c-kzg"
    );

    let out = serde_json::json!({
        "_purpose": "REAL KZG opening for the forge suite; generated by tools/kzg-fixture — never hand-edit",
        "instance": hx(&INSTANCE),
        "priorLeafCount": n0,
        "newLeafCount": n0 + m,
        "priorPeaks": prior_peaks.iter().map(|p| hx(p)).collect::<Vec<_>>(),
        "newSubtreePeaks": subtrees.iter().map(|p| hx(p)).collect::<Vec<_>>(),
        "blobVersionedHashes": [hx(&vh)],
        "commitment": hx(commitment.to_bytes().as_slice()),
        "kzgProof": hx(proof.to_bytes().as_slice()),
        "y": hx(y.as_slice()),
        "z": hx(&z),
    });

    let path = format!(
        "{}/../../contracts/test/fixtures/{file}",
        env!("CARGO_MANIFEST_DIR")
    );
    std::fs::write(&path, format!("{}\n", serde_json::to_string_pretty(&out).unwrap()))
        .expect("write fixture");
    println!("wrote contracts/test/fixtures/{file}");
}

fn main() {
    emit_fixture(5, 3, "kzg_opening.json");
    emit_fixture(0, 8, "kzg_opening_genesis.json");
}
